# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # Docs: https://docs.github.com/en/rest/reference/repos#update-a-repository
  name: awesome-computercraft
  description: Useful libraries, programs, literature, and mods for ComputerCraft and its forks. 
  homepage: null
  topics: minecraft, awesome, computercraft, awesome-list, computercraft-tweaked
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

collaborators:
  - username: MCJack123
  - username: totallynotmarcus
  # Maybe you?
